Fix a little

diff --git a/modify-android-uri b/modify-android-uri
--- a/modify-android-uri
+++ b/modify-android-uri
@@ -2,7 +2,7 @@
 
 if [ $# -lt 1 ]
 then
-  echo '1 argument (url) is required.' 1>&2
+  echo '1 argument (url) is required.' >&2
   exit 1
 fi
 
